import { createTransport } from 'nodemailer';
import type { SmtpConfig, TestReport } from '../config/types.js';

/**
 * Send test report via email (SMTP).
 */
export async function sendEmail(
  smtp: SmtpConfig,
  to: string[],
  report: TestReport
): Promise<void> {
  const transporter = createTransport({
    host: smtp.host,
    port: smtp.port,
    secure: smtp.secure ?? smtp.port === 465,
    auth: {
      user: smtp.user,
      pass: smtp.pass,
    },
  });

  const statusEmoji = report.failed > 0 ? '❌' : '✅';
  const subject = `${statusEmoji} omni-qa 测试报告 [${report.env}] - ${report.passed}/${report.total} passed`;

  const html = buildHtmlReport(report);

  await transporter.sendMail({
    from: smtp.user,
    to: to.join(', '),
    subject,
    html,
  });
}

function buildHtmlReport(report: TestReport): string {
  const failureRows = report.failures
    .map(
      (f) => `
      <tr style="background:#FEE2E2">
        <td style="padding:8px;border:1px solid #ddd">${f.endpoint}</td>
        <td style="padding:8px;border:1px solid #ddd">${f.title}</td>
        <td style="padding:8px;border:1px solid #ddd"><code>${escapeHtml(f.error)}</code></td>
      </tr>`
    )
    .join('');

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px">
  <h2 style="color:#1a1a1a">omni-qa 测试报告</h2>

  <table style="width:100%;margin:16px 0">
    <tr><td><strong>环境</strong></td><td>${report.env}</td></tr>
    <tr><td><strong>时间</strong></td><td>${report.timestamp}</td></tr>
    <tr><td><strong>耗时</strong></td><td>${formatDuration(report.duration)}</td></tr>
  </table>

  <table style="width:100%;border-collapse:collapse;margin:16px 0">
    <tr style="background:#F3F4F6">
      <th style="padding:10px;border:1px solid #ddd;text-align:left">状态</th>
      <th style="padding:10px;border:1px solid #ddd;text-align:right">数量</th>
    </tr>
    <tr>
      <td style="padding:8px;border:1px solid #ddd">✅ 通过</td>
      <td style="padding:8px;border:1px solid #ddd;text-align:right;color:#16A34A"><strong>${report.passed}</strong></td>
    </tr>
    <tr>
      <td style="padding:8px;border:1px solid #ddd">❌ 失败</td>
      <td style="padding:8px;border:1px solid #ddd;text-align:right;color:#DC2626"><strong>${report.failed}</strong></td>
    </tr>
    <tr>
      <td style="padding:8px;border:1px solid #ddd">⏭️ 跳过</td>
      <td style="padding:8px;border:1px solid #ddd;text-align:right">${report.skipped}</td>
    </tr>
    <tr style="background:#F3F4F6">
      <td style="padding:8px;border:1px solid #ddd"><strong>总计</strong></td>
      <td style="padding:8px;border:1px solid #ddd;text-align:right"><strong>${report.total}</strong></td>
    </tr>
  </table>

  ${
    report.failures.length > 0
      ? `
  <h3 style="color:#DC2626">失败详情</h3>
  <table style="width:100%;border-collapse:collapse;margin:16px 0">
    <tr style="background:#F3F4F6">
      <th style="padding:10px;border:1px solid #ddd;text-align:left">接口</th>
      <th style="padding:10px;border:1px solid #ddd;text-align:left">用例</th>
      <th style="padding:10px;border:1px solid #ddd;text-align:left">错误</th>
    </tr>
    ${failureRows}
  </table>`
      : '<p style="color:#16A34A"><strong>全部通过！🎉</strong></p>'
  }

  <hr style="border:none;border-top:1px solid #E5E7EB;margin:24px 0">
  <p style="color:#9CA3AF;font-size:12px">Generated by omni-qa</p>
</body>
</html>`;
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  const seconds = Math.floor(ms / 1000);
  if (seconds < 60) return `${seconds}s`;
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  return `${minutes}m ${remainingSeconds}s`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
